export function renderProxyHelp(): string {
  return [
    "ClaimLatch OpenAI-compatible verification proxy",
    "",
    "Usage:",
    "  claimlatch-proxy",
    "",
    "Required environment variables:",
    "  CLAIMLATCH_PROXY_UPSTREAM_BASE_URL  Generation provider base URL",
    "  CLAIMLATCH_LLM_MODEL                 Verification model",
    "  TAVILY_API_KEY                       Evidence search credential",
    "",
    "Optional environment variables:",
    "  CLAIMLATCH_PROXY_UPSTREAM_API_KEY   Upstream provider credential",
    "  CLAIMLATCH_LLM_API_KEY               Verification model credential",
    "  CLAIMLATCH_PROXY_HOST / _PORT        Bind host and port (127.0.0.1 / 4317)",
    "  CLAIMLATCH_PROXY_UPSTREAM_API_KEY_HEADER",
    "  CLAIMLATCH_PROXY_UPSTREAM_CHAT_COMPLETIONS_PATH",
    "  CLAIMLATCH_PROXY_UPSTREAM_REQUEST_HEADERS   Comma-separated name=value headers",
    "  CLAIMLATCH_PROXY_UPSTREAM_RESPONSE_HEADER_NAMES",
    "  CLAIMLATCH_PROXY_UPSTREAM_RESPONSE_HEADER_PREFIXES",
    "  CLAIMLATCH_PROXY_UPSTREAM_TIMEOUT_MS",
    "  CLAIMLATCH_REQUIRE_DOCUMENT_PROVENANCE",
    "",
    "Routes:",
    "  GET  /health",
    "  POST /v1/chat/completions",
    "  POST /chat/completions",
    "",
    "PASS releases the verified completion. BLOCK returns HTTP 422.",
    "Malformed, unsupported, truncated, or unverifiable responses fail closed.",
    "This credential-free claimlatch-proxy --help command displays this help without credentials.",
    "",
  ].join("\n");
}
